//TicTacToe Game Class
class TicTacToe {
    //MODEL
    constructor() { // <-- i will need to put things in constructor
        //example of game array
        // this.array = [
        //     [0, 0, 0],
        //     [0, 0, 0],
        //     [0, 0, 0],
        // ];

        this.gridArray = [];

        //linking dynamic rendering to html
        this.app = document.getElementById("app");

        //gameExists? boolean
        let gameExists = true;

        //winConditions
        //tie? -- if winConditions are not met, it must be a tie
        //placement of x and o

        //number of turns -- check win conditions after 5 turns or more
        this.numTurn = 0;

        if(this.numTurn > 4) {
            winConditions();
        }

        //gameOver
        let winText;
        //gameOver() {
            // IF playerX meets winConditions(){
            //     winText.innerText = "Player X has won the game!"
            // } ELSE IF playerO meets winConditions(){
            //     winText.innerText = "Player O has won the game!"
            // } ELSE {
            //     tieMethod();
            // }
        //}
        let tieText;
        // tieMethod() {
        //     tieText.innerText = "Game has ended in a tie."
        // }

        //restart
        // restartBtnMethod() {
        //     restart();
        // }
    }

    //VIEW METHODS
    generateView() {
        //procedural rendering
        let container = this.generateHTML({ type: 'div', classes: 'container', parent: this.app });
        let row = this.generateHTML({ type: 'div', classes: 'row', parent: container, styles: '', id: 0 });
        //let col = generateHTML({ type: 'div', classes: 'col-4 text-center border border-dark lh-lg', parent: row, text: "", styles: 'min-width: 14vw; min-height: 16vw; font-size: 8vw', id: index });

        //dynamic rendering
        for (let index = 0; index < 9; index++) {
            let col = this.generateHTML({ type: 'div', classes: 'col-4 text-center border border-dark lh-lg', parent: row, text: "", styles: 'min-width: 16vw; min-height: 14vw;', id: index });
            let button = this.generateHTML({ type: 'button', classes: 'btn', parent: col, text: "", styles: 'min-width: 100%; min-height: 99%; font-size: 8vw;', text: "", onclick: this.handleClick.bind(this, index) });
            let tile = new Tile(button, index);
            this.gridArray.push(tile);
            //save tile object as well
        }

//      //variables that will get elements from Tile class and pull it's button attribute
        // let tiles = document.getElementsByClassName("Tile");
        // let attribute = tiles.getAttribute(tileBtn);
    }

    //method to create objects for dynamic rendering
    generateHTML({ type, classes, parent = null, text = '', styles, id, onclick }) {
        let element = document.createElement(type);
        element.className = classes;
        element.innerText = text;
        element.style = styles;
        element.id = id;
        element.onclick = onclick;

        // TODO:
        // event listeners
        // value, data, clicked

        if (parent) {
            parent.appendChild(element);
        }

        return element;
    }

    updateView() {
        
    }

    //show win or tie
    //gameOver();

    //show current player
    currentPlayer(){
        if (this.numTurn % 2 == 0) {
            playerTurn.innerText = "It's player O's turn.";
        } else {
            playerTurn.innerText = "It's player X's turn.";
        }
    }

    //CONTROLLER METHODS
    init() {
        console.log("init(TicTacToe)");

    }

    handleClick(index) {
        //console.log(this.gridArray[index]);
        if (!this.gridArray[index].wasClicked) {
            this.checkTurn(index);
            this.currentPlayer();
            this.numTurn++;
            this.gridArray[index].wasClicked = true;
        }
    }

    //whose turn is it?
    checkTurn(index) {
        //console.log(this.numTurn, this.gridArray, index);
        if (this.numTurn % 2 == 0){
            this.gridArray[index].element.innerText = "X";
        } else {
            this.gridArray[index].element.innerText = "O";
        }
    }

    //restart button
    restart() {
        init();
    }

    //check for win
    // IF a row, col, or diag are >= 3 AND no values are empty
    // winConditions();

    //update grid
        //show win or tie?
        //show current player?
    //update winner?
}


//Individual Tile Class
class Tile {
    //MODEL
    constructor(element, index) {
        this.element = element;
        this.index = index;
        this.wasClicked = false;
        this.who = "nobody";
    }

    //VIEW METHODS
    updateView() {
        //create tile?

        //render x or o
        // Look in parent
        if (xTurn) {
            xDraw.innerText = "X";
        } else {
            oDraw.innerText = "O";
        }

    }
    
    //CONTROLLER METHODS
    //view is generated by the parent
    handleClick(e) {
        //onclick -- run view method and methods from parent
        tileClick.addEventListener('click', updateView);

    }
    
}

//initializing page
function init() { //we want to reset the board first, then generate the view
    let game = new TicTacToe();
    game.generateView();
}

init();